### ISSUE TITLE
filter.js should return either null or an Error object

### ISSUE THREAD

**Issue by gtrainavicius** [Quoorex/docker-bittorrent-tracker#5]
Hey, I tried out the tracker - it worked, but I noticed huge amount of requests coming in with unknown hashes, and they were getting through, regardless of the whitelist that was configured. So the issue is that filter.js should return `null` or `new Error(...)` instead.

See https://github.com/webtorrent/bittorrent-tracker/blob/master/README.md#server:

```
    var allowed = (infoHash === 'aaa67059ed6bd08362da625b3ae77f6f4a075aaa')
    if (allowed) {
      // If the callback is passed `null`, the torrent will be allowed.
      cb(null)
    } else {
      // If the callback is passed an `Error` object, the torrent will be disallowed
      // and the error's `message` property will be given as the reason.
      cb(new Error('disallowed torrent'))
    }
```

**Comment by Quoorex** [comment]
I appreciate your contribution.
I've addressed this issue in the latest commits. Please provide me with feedback whether it's working for you now.

**Comment by gtrainavicius** [comment]
The changes look correct, that's pretty much how I had it fixed locally. We won't need to run a torrent tracker after all, so I can't check your changes out anymore. :)
